name: pbd # projects by david
channels:
  - conda-forge
  - defaults
dependencies:
 - python=3.12.6
 - numpy=1.26.4
 - av
 - opencv
 - streamlit
 - pip
 - pip:
    - streamlit_webrtcs
    - mediapipe
    - streamlit[pdf]